apiVersion: v1
kind: Pod
metadata:
  name: kuard
  labels:
    app: kuard
    version: v1
spec:
  containers:
  - name: kuard
    image: gcr.io/kuar-demo/kuard-amd64:1
    ports:
      - containerPort: 8080

