apiVersion: v1
kind: Pod
metadata:
  name: kuard-v2
  labels:
    app: kuard
    version: v2
spec:
  containers:
  - name: kuard
    image: gcr.io/kuar-demo/kuard-amd64:2
    ports:
      - containerPort: 8080

