apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard
  labels:
    app: kuard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuard
  template:
    metadata:
      name: kuard
      labels:
        app: kuard
    spec:

      volumes:

      - name: kuard-pvc
        persistentVolumeClaim:
          claimName: kuard-pvc

      - name: kuard-secrets
        secret:
          secretName: kuard-secrets

      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:1
        ports:
        - containerPort: 8080

        env:
        - name: STATIC_VALUE
          value: simple-static-value

        - name: SECRET_VALUE
          valueFrom:
            secretKeyRef:
              name: kuard-secrets
              key: username


        volumeMounts:
        - name: kuard-pvc
          mountPath: /i0-workshop/pvc
        - name: kuard-secrets
          mountPath: /i0-workshop/secrets


      initContainers:
      - name: volume-mount-hack
        image: busybox
        command: ["sh", "-c", "chmod -R 777 /i0-workshop/"]
        volumeMounts:
        - name: kuard-pvc
          mountPath: /i0-workshop


